# Generated by Django 2.2.13 on 2020-06-09 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('isFolder', models.BooleanField()),
                ('path', models.TextField()),
                ('owner', models.CharField(default='', max_length=30, null=True)),
                ('filesize', models.CharField(max_length=10)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedDate', models.CharField(blank=True, max_length=10, null=True)),
                ('share', models.BooleanField(default=False)),
                ('cid', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['createdDate'],
            },
        ),
    ]
