# Generated by Django 2.2.13 on 2020-06-15 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud', '0002_starfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('owner', models.CharField(default='', max_length=30, null=True)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ShareUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareFolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.ShareFolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShareFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.File')),
                ('shareFolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.ShareFolder')),
            ],
        ),
    ]
